/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddIcon: typeof import('./src/components/icons/AddIcon.vue')['default']
    ArrowDown: typeof import('./src/components/icons/ArrowDown.vue')['default']
    ArrowLeft: typeof import('./src/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./src/components/icons/ArrowRight.vue')['default']
    ArrowUp: typeof import('./src/components/icons/ArrowUp.vue')['default']
    AuthWrapper: typeof import('./src/components/templates/AuthWrapper.vue')['default']
    BaseButton: typeof import('./src/components/atom/BaseButton.vue')['default']
    BigCard: typeof import('./src/components/molecules/BigCard.vue')['default']
    Browse: typeof import('./src/components/templates/Browse.vue')['default']
    BrowseFilterGameList: typeof import('./src/components/organism/BrowseFilterGameList.vue')['default']
    BrowsePagination: typeof import('./src/components/atom/BrowsePagination.vue')['default']
    Checkable: typeof import('./src/components/atom/Checkable.vue')['default']
    Checkbox: typeof import('./src/components/atom/Checkbox.vue')['default']
    CheckIcon: typeof import('./src/components/icons/CheckIcon.vue')['default']
    Collapse: typeof import('./src/components/molecules/Collapse.vue')['default']
    CrossIcon: typeof import('./src/components/icons/CrossIcon.vue')['default']
    Discover: typeof import('./src/components/templates/Discover.vue')['default']
    Dropdown: typeof import('./src/components/atom/Dropdown.vue')['default']
    DropdownInput: typeof import('./src/components/atom/DropdownInput.vue')['default']
    EpicGames: typeof import('./src/components/icons/EpicGames.vue')['default']
    EyeIcon: typeof import('./src/components/icons/EyeIcon.vue')['default']
    EyeOffIcon: typeof import('./src/components/icons/EyeOffIcon.vue')['default']
    Facebook: typeof import('./src/components/icons/Facebook.vue')['default']
    FilterIcon: typeof import('./src/components/icons/FilterIcon.vue')['default']
    FloatingInput: typeof import('./src/components/atom/FloatingInput.vue')['default']
    Footer: typeof import('./src/components/templates/Footer.vue')['default']
    FreeGames: typeof import('./src/components/organism/FreeGames.vue')['default']
    GameCard: typeof import('./src/components/molecules/GameCard.vue')['default']
    GameList: typeof import('./src/components/organism/GameList.vue')['default']
    GameOnSale: typeof import('./src/components/organism/GameOnSale.vue')['default']
    GamePosts: typeof import('./src/components/organism/GamePosts.vue')['default']
    GamesWithStatus: typeof import('./src/components/organism/GamesWithStatus.vue')['default']
    Globe: typeof import('./src/components/icons/Globe.vue')['default']
    HamburgerMenu: typeof import('./src/components/icons/HamburgerMenu.vue')['default']
    HighlightGame: typeof import('./src/components/organism/HighlightGame.vue')['default']
    HighlightGameImage: typeof import('./src/components/organism/HighlightGameImage.vue')['default']
    HighlightGameList: typeof import('./src/components/organism/HighlightGameList.vue')['default']
    IconGift: typeof import('./src/components/icons/IconGift.vue')['default']
    Logo: typeof import('./src/components/atom/Logo.vue')['default']
    MainLayout: typeof import('./src/components/layouts/MainLayout.vue')['default']
    MenuItem: typeof import('./src/components/atom/MenuItem.vue')['default']
    MobileFilterOption: typeof import('./src/components/molecules/MobileFilterOption.vue')['default']
    MobileSearch: typeof import('./src/components/molecules/MobileSearch.vue')['default']
    Navbar: typeof import('./src/components/templates/Navbar.vue')['default']
    Overlay: typeof import('./src/components/atom/Overlay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search: typeof import('./src/components/icons/Search.vue')['default']
    SearchInput: typeof import('./src/components/molecules/SearchInput.vue')['default']
    TabMenu: typeof import('./src/components/molecules/TabMenu.vue')['default']
    ToggleMenu: typeof import('./src/components/atom/ToggleMenu.vue')['default']
    Twitter: typeof import('./src/components/icons/Twitter.vue')['default']
    UnrealEngine: typeof import('./src/components/icons/UnrealEngine.vue')['default']
    User: typeof import('./src/components/icons/User.vue')['default']
    Youtube: typeof import('./src/components/icons/Youtube.vue')['default']
  }
}
